name: Test
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: ricardo-jorge-correia/hello-world-docker-action@v1
        with:
          who-to-greet: '@correia'
